// ALERT REDUCER
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// EXERCISE REDUCER
export const SET_EXERCISES = 'SET_EXERCISES';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const SET_EXERCISE = 'SET_EXERCISE';
export const CLEAR_EXCERCISE = 'CLEAR_EXCERCISE';
export const EXERCISE_ERROR = 'EXERCISE_ERROR';

// USERS REDUCER
export const GET_USERS = 'GET_USERS';
export const USER_ERROR = 'USER_ERROR';